---
- name: Update certificate trust
  ansible.builtin.command:
    # This handler only runs when the content of the certificates
    # directory is updated by the copy task in the playbook
    cmd: "{{ update_ca_trust_command }}" # noqa no-changed-when
