---
- name: Converge
  hosts: all
<<<<<<< HEAD
  roles:
    - role: ansible-role-dhs-certificates
=======
  tasks:
    - name: Include skeleton-ansible-role
      ansible.builtin.include_role:
        name: skeleton-ansible-role
>>>>>>> e25720218335832b4dda2287086ee9e91b778ff0
